--separate table for state city rivers

--state table
CREATE TABLE STATE(
RG_ID NUMBER PRIMARY KEY,
NAME VARCHAR2(32),
SHAPE MDSYS.SDO_GEOMETRY
);

--city table
CREATE TABLE CITY(
RG_ID NUMBER PRIMARY KEY,
NAME VARCHAR2(32),
SHAPE MDSYS.SDO_GEOMETRY
);

--river table
CREATE TABLE RIVER(
RG_ID NUMBER PRIMARY KEY,
NAME VARCHAR2(32),
SHAPE MDSYS.SDO_GEOMETRY
);
--ALL GEOMETRY CONSIDERED AS EXTERIOR
--INSERTING STATES
INSERT INTO STATE VALUES(
    1,
    'STATE_1',
    MDSYS.SDO_GEOMETRY(
        2003,
        NULL,
        NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1),
        MDSYS.SDO_ORDINATE_ARRAY(10,10 , 50,10 , 60,60 ,10,40 ,10,10)
    )
);

INSERT INTO STATE VALUES(
    2,
    'STATE_2',
    MDSYS.SDO_GEOMETRY(
        2003,
        NULL,
        NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,3),
        MDSYS.SDO_ORDINATE_ARRAY(100,20 , 150,50)
    )
);

--INSERTNG CITIES
INSERT INTO CITY VALUES(
    1,
    'CITY_1',
    MDSYS.SDO_GEOMETRY(
        2003,
        NULL,
        NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,4),
        MDSYS.SDO_ORDINATE_ARRAY(15,30 , 20,35 , 15,40)
    )
);

INSERT INTO CITY VALUES(
    2,
    'CITY_2',
    MDSYS.SDO_GEOMETRY(
        2003,
        NULL,
        NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,4),
        MDSYS.SDO_ORDINATE_ARRAY(22,33 , 24,35 , 22,37)
    )
);

INSERT INTO CITY VALUES(
    3,
    'CITY_3',
    MDSYS.SDO_GEOMETRY(
        2001,
        NULL,
        NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,1,1),
        MDSYS.SDO_ORDINATE_ARRAY(55,40)
    )
);

INSERT INTO CITY VALUES(
    4,
    'CITY_4',
    MDSYS.SDO_GEOMETRY(
        2003,
        NULL,
        NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,3),
        MDSYS.SDO_ORDINATE_ARRAY(40,15 , 55,30)
    )
);

INSERT INTO CITY VALUES(
    5,
    'CITY_5',
    MDSYS.SDO_GEOMETRY(
        2003,
        NULL,
        NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,3),
        MDSYS.SDO_ORDINATE_ARRAY(120,30 , 130,40)
    )
);

--INSERTING RIVERS
INSERT INTO RIVER VALUES(
    1,
    'RIVER_1',
    MDSYS.SDO_GEOMETRY(
        2002,
        NULL,
        NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),
        MDSYS.SDO_ORDINATE_ARRAY(15,25 , 52,58)
    )
);

INSERT INTO RIVER VALUES(
    2,
    'RIVER_2',
    MDSYS.SDO_GEOMETRY(
        2002,
        NULL,
        NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),
        MDSYS.SDO_ORDINATE_ARRAY(10,30 , 60,45)
    )
);

INSERT INTO RIVER VALUES(
    3,
    'RIVER_3',
    MDSYS.SDO_GEOMETRY(
        2002,
        NULL,
        NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),
        MDSYS.SDO_ORDINATE_ARRAY(55,30 , 110,30)
    )
);

SELECT * FROM RIVER ORDER BY RG_ID;
-- INSERT INTO USER_SDO_GEOM_METADATA FIRST BEFORE CREATING INDEX
--CREATING INDEX STATE
CREATE INDEX
STATE_IDX
ON STATE(SHAPE)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

--CREATING INDEX CITY
CREATE INDEX
CITY_IDX
ON CITY(SHAPE)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

--CREATING INDEX RIVER
CREATE INDEX
RIVER_IDX
ON RIVER(SHAPE)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

--QUESTIONS
--1. Locate all cities in state ‘st1’ 
SELECT
S.NAME "STATE",
C.NAME "CITY"
FROM STATE S, CITY C
WHERE
S.NAME='STATE_1'
AND
SDO_GEOM.RELATE
(S.SHAPE,'CONTAINS OR COVERS',C.NAME)='CONTAINS OR COVERS';