CREATE TABLE REGION(
RG_ID NUMBER PRIMARY KEY,
NAME VARCHAR2(32),
TYPE VARCHAR2(32),
SHAPE MDSYS.SDO_GEOMETRY
);

DROP TABLE REGION;

INSERT INTO REGION VALUES(
    1,
    'STATE_1',
				'STATE',
    MDSYS.SDO_GEOMETRY(
        2003,
        NULL,
        NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1),
        MDSYS.SDO_ORDINATE_ARRAY(10,10 , 50,10 , 60,60 ,10,40 ,10,10)
    )
);

INSERT INTO REGION VALUES(
    2,
    'STATE_2',
				'STATE',
    MDSYS.SDO_GEOMETRY(
        2003,
        NULL,
        NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,3),
        MDSYS.SDO_ORDINATE_ARRAY(100,20 , 150,50)
    )
);

INSERT INTO REGION VALUES(
    3,
    'CITY_1',
				'CITY',
    MDSYS.SDO_GEOMETRY(
        2003,
        NULL,
        NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,4),
        MDSYS.SDO_ORDINATE_ARRAY(15,30 , 20,35 , 15,40)
    )
);

INSERT INTO REGION VALUES(
    4,
    'CITY_2',
				'CITY',
    MDSYS.SDO_GEOMETRY(
        2003,
        NULL,
        NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,4),
        MDSYS.SDO_ORDINATE_ARRAY(22,33 , 24,35 , 22,37)
    )
);

INSERT INTO REGION VALUES(
    5,
    'CITY_3',
				'CITY',
    MDSYS.SDO_GEOMETRY(
        2001,
        NULL,
        NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,1,1),
        MDSYS.SDO_ORDINATE_ARRAY(55,40)
    )
);

INSERT INTO REGION VALUES(
    6,
    'CITY_4',
				'CITY',
    MDSYS.SDO_GEOMETRY(
        2003,
        NULL,
        NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,3),
        MDSYS.SDO_ORDINATE_ARRAY(40,15 , 55,30)
    )
);

INSERT INTO REGION VALUES(
    7,
    'CITY_5',
				'CITY',
    MDSYS.SDO_GEOMETRY(
        2003,
        NULL,
        NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,3),
        MDSYS.SDO_ORDINATE_ARRAY(120,30 , 130,40)
    )
);

INSERT INTO REGION VALUES(
    8,
    'RIVER_1',
				'RIVER',
    MDSYS.SDO_GEOMETRY(
        2002,
        NULL,
        NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),
        MDSYS.SDO_ORDINATE_ARRAY(15,25 , 52,58)
    )
);

INSERT INTO REGION VALUES(
    9,
    'RIVER_2',
				'RIVER',
    MDSYS.SDO_GEOMETRY(
        2002,
        NULL,
        NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),
        MDSYS.SDO_ORDINATE_ARRAY(10,30 , 60,45)
    )
);

INSERT INTO REGION VALUES(
    10,
    'RIVER_3',
				'RIVER',
    MDSYS.SDO_GEOMETRY(
        2002,
        NULL,
        NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),
        MDSYS.SDO_ORDINATE_ARRAY(55,30 , 110,30)
    )
);

SELECT
*
FROM
REGION;

--updating meta deta 
INSERT INTO USER_SDO_GEOM_METADATA VALUES (
  'REGION',
  'SHAPE',
  MDSYS.SDO_DIM_ARRAY(   
    MDSYS.SDO_DIM_ELEMENT('X', 0, 180, 0.005),
    MDSYS.SDO_DIM_ELEMENT('Y', 0, 180, 0.005)
     ),
  NULL
);

SELECT * FROM USER_SDO_GEOM_METADATA;

CREATE INDEX
REGION_IDX
ON REGION(SHAPE)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

SELECT 
r.name,
SDO_GEOM.RELATE(S.SHAPE, 'DETERMINE', R.SHAPE)
FROM REGION S, REGION R
WHERE 
S.NAME='STATE_2'; --'STATE_1'

--1. Locate all cities in state ‘st1’ 

SELECT 
R.NAME,
SDO_GEOM.RELATE
(S.SHAPE,'DETERMINE',R.SHAPE) "RELATION TYPE"
FROM REGION S, REGION R
WHERE
S.NAME='STATE_1'
AND 
R.TYPE='CITY'
AND
SDO_GEOM.RELATE
(S.SHAPE,'CONTAINS OR COVERS',R.SHAPE)='CONTAINS OR COVERS';



--2. Locate all cities in state ‘st2’ 
SELECT 
R.NAME, SDO_GEOM.RELATE(S.SHAPE,'DETERMINE',R.SHAPE)"RELATION TYPE"
FROM REGION R, REGION S
WHERE
S.NAME='STATE_2'
AND 
R.TYPE='CITY'
AND
SDO_GEOM.RELATE
(S.SHAPE,'CONTAINS OR COVERS', R.SHAPE)='CONTAINS OR COVERS';


--3. Locate all cities not more than 10km from ‘c3’
--REFF
SELECT SDO_GEOM.WITHIN_DISTANCE(c_b.shape, m.diminfo, 1,
     c_d.shape, m.diminfo) 
  FROM cola_markets c_b, cola_markets c_d, user_sdo_geom_metadata m 
  WHERE m.table_name = 'COLA_MARKETS' AND m.column_name = 'SHAPE' 
  AND c_b.name = 'cola_b' AND c_d.name = 'cola_d';

--	QUERY
SELECT
R.NAME,
SDO_GEOM.WITHIN_DISTANCE(C.SHAPE,10,R.SHAPE)"CITIES WITHIN 10KM OF CITY_3"
FROM REGION R, REGION C
WHERE C.NAME='CITY_3'
AND 
R.TYPE='CITY'
AND
SDO_GEOM.WITHIN_DISTANCE(C.SHAPE,10,R.SHAPE)='TRUE';
--- this returns all the regions inside or on 10km boundary of c3
--- includes state_1, city_3, city_4, RIVER_2, RIVER_3
--end

--4. Locate the cities touching city ‘c2’
SELECT 
R.NAME, 
SDO_GEOM.RELATE(C.SHAPE,'DETERMINE',R.SHAPE)"CITY RELATION"
FROM REGION R, REGION C
WHERE
C.NAME='CITY_2'
AND 
R.TYPE='CITY'
AND
SDO_GEOM.RELATE(C.SHAPE,'TOUCH',R.SHAPE)='TOUCH';

--5. locate city within 5km from r2
SELECT 
R.NAME,
SDO_GEOM.WITHIN_DISTANCE(C.SHAPE,5,R.SHAPE)"CITY WITHIN 5KM OF RIVER_2"
FROM REGION R, REGION C
WHERE 
C.NAME='RIVER_2'
AND 
R.TYPE='CITY'
AND
SDO_GEOM.WITHIN_DISTANCE(C.SHAPE,5,R.SHAPE)='TRUE';
--ADD MORE COLUMN TYPE TYPE REGION
--6. Locate cities intersected by river ‘r2’
SELECT
R.NAME,
SDO_GEOM.RELATE(R.SHAPE,'OVERLAPBDYINTERSECT',C.SHAPE)
FROM REGION R, REGION C
WHERE
C.NAME='RIVER_2'
AND 
R.TYPE='CITY'
AND
SDO_GEOM.RELATE(C.SHAPE,'OVERLAPBDYINTERSECT',R.SHAPE)='OVERLAPBDYINTERSECT';
-- gives only state, maybe problem in city coordinates or different relate mask

--BY INTERSECTION
SELECT
R.NAME
,SDO_GEOM.RELATE(C.SHAPE,'DETERMINE',R.SHAPE)"CITY RELATION TYPE WITH RIVER_2"
FROM REGION R, REGION C
WHERE C.NAME='RIVER_2'
AND 
R.TYPE='CITY'
AND SDO_GEOM.SDO_INTERSECTION(C.SHAPE,R.SHAPE,0.005)IS NOT NULL;

SELECT
R.NAME,
SDO_GEOM.RELATE(R.SHAPE,'DETERMINE',C.SHAPE)
FROM REGION R, REGION C
WHERE
C.NAME='RIVER_2'
AND
SDO_GEOM.RELATE(C.SHAPE,'ANYINTERACT',R.SHAPE)='TRUE';
--THIS GIVES ALL THE RELATE BETWEEN R2 AND OTHER regions
--end

--7.	 Find cities intersected by ‘r3’
--REFF
SELECT
R.NAME,
SDO_GEOM.RELATE(R.SHAPE,'DETERMINE',C.SHAPE)
FROM REGION R, REGION C
WHERE
C.NAME='RIVER_3'
AND
SDO_GEOM.RELATE(C.SHAPE,'ANYINTERACT',R.SHAPE)='TRUE';
--none..just intersects state_2, relate given by OVERLAPBDYDISJOINT
--maybe problem with interior or exterior, coordinates, 
-- BY INTERSECT
SELECT
R.NAME
,SDO_GEOM.RELATE(C.SHAPE,'DETERMINE',R.SHAPE)"CITIES RELATION TO RIVER_3"
FROM REGION R, REGION C
WHERE C.NAME='RIVER_3'
AND 
R.TYPE='CITY'
AND SDO_GEOM.SDO_INTERSECTION(C.SHAPE,R.SHAPE,0.005)IS NOT NULL;
--end

--8.	Find the population in every city of state ‘st1’ if the population per sq. km. is 6.
--select every city in state_1 then find area of each city multiply by 6
-- look into begin if else end struture of queries for direct ans
SELECT 
R.NAME,
SDO_GEOM.SDO_AREA(R.SHAPE, 0.005)"AREA"
FROM REGION S, REGION R
WHERE
R.TYPE='CITY'
AND 
S.NAME='STATE_1'
AND
SDO_GEOM.RELATE
(S.SHAPE,'CONTAINS OR COVERS',R.SHAPE)='CONTAINS OR COVERS';

SELECT name, SDO_GEOM.SDO_AREA(shape, 0.005) FROM REGION;

--9.	Find distance between two states.
SELECT 
SDO_GEOM.SDO_DISTANCE(S1.SHAPE,S2.SHAPE) "DISTANCE BETWEEN STATE_1 AND STATE_2"
FROM REGION S1, REGION S2
WHERE
S1.NAME='STATE_1'
AND
S2.NAME='STATE_2';